---
- name: Restart AdGuardHome
  ansible.builtin.systemd:
    name: AdGuardHome
    state: restarted
  listen: Restart AdGuardHome

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  listen: Restart systemd-resolved
