---
- name: Restart AdGuardHome
  ansible.builtin.systemd:
    name: AdGuardHome
    state: restarted

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
